version: '3'

dotenv: ['.env', 'secrets/.env']

tasks:
  agent-start:
    desc: Test
    cmds: 
      - |
        docker run --rm --name my_tfc_agent -e TFC_AGENT_TOKEN \
          -v /var/run/docker.sock:/var/run/docker.sock \
          hashicorp/tfc-agent:latest
  
  broker-start:
    desc: Test
    cmds:
      - |
        docker run -d --rm \
          --name broker \
          -p 3000:3000  -v `pwd`:/data  \
          williamyeh/json-server        \
          --watch db.json